### ISSUE TITLE
Doesn't work at all in Chrome?

### ISSUE THREAD

**Issue by thesourmango** [arcada-uas/TechLabs-ZephyrChat#2]
Getting a res.body is not an async iterable error in chrome
![image](https://github.com/arcada-uas/TechLabs-ZephyrChat/assets/6995847/21ad197f-5987-46c5-b4e8-6c6dabcc7295)

The issue is here:
![image](https://github.com/arcada-uas/TechLabs-ZephyrChat/assets/6995847/6322a0bf-256b-4a8a-93b7-dc68640aef1a)
Andrey sent me to https://javascript.info/async-iterators-generators but I don't get it.

Googling since its a chrome only issue I found problems with async iterators on chrome since 2017
https://jakearchibald.com/2017/async-iterators-and-generators/
And an open issue on readablestream iteration https://bugs.chromium.org/p/chromium/issues/detail?id=929585
But I'm not sure that's the issue. Plz help

**Comment by parland** [comment]
fixed

**Comment by parland** [comment]
@thesourmango соuld you please update the code that gets out the interface in the production environment?

**Comment by thesourmango** [comment]
Great work @parland thanks! Absolutely, the fix is now live!
Unfortunately I worked on the openai endpoint around the same time as you worked on this, so the new OpenAI endpoint in the openai branch (now default) still has this issue heh

For future reference, the issue was chrome not supporting async iteration of a stream using for await .. of
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#async_iteration_of_a_stream_using_for_await...of

I'm opening a separate issue for the openai implementation as the title of this issue is misleading
